=== faiqahmed56/xml/employees.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="employees">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="employee" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="id"></xs:element>
                        <xs:element name="name"></xs:element>
                        <xs:element name="department"></xs:element>
                        <xs:element name="courses">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="course"></xs:element>
                                    <xs:element name="course"></xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        </xs:complexType>
        
    </xs:element>
</xs:schema>

=== faiqahmed56/xml/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="employees.xsd">
    <employee>
        <id>01</id>
        <name>faiq</name>
        <department>staff</department>
        <courses>
            <course>CPISM</course>
            <course>DISM</course>
        </courses>
    </employee>
    <employee>
        <id>02</id>
        <name>dabeer</name>
        <department>management</department>
        <courses>
            <course>CPISM</course>
            <course>DISM</course>
        </courses>
    </employee><employee>
        <id>03</id>
        <name>hammal</name>
        <department>it</department>
        <courses>
            <course>CPISM</course>
            <course>DISM</course>
        </courses>
    </employee>
</employees>
